### ISSUE TITLE
How do I change the header layout?

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#12]
There's no option in Elementor, but I see the options inside the Customizer.

**Comment by cristianraiber** [comment]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/7841556/46742250-4ee87380-ccaf-11e8-9344-4e1359c3a493.png">

**Comment by codepixar** [comment]
@cristianraiber Sorry for inconvenience. To change header layout please follow this screen short.

http://prntscr.com/l698jm

**Comment by cristianraiber** [comment]
@codepixar - is the header layout set per page or globally? If it's globally, move this option into the Customizer, please. Right now, it's not clear where/what you have to do to change the header layout.

**Comment by codepixar** [comment]
@cristianraiber - The header layout set only for custom page. When user use custom page using  the template ( template builder page ) they can change header layout on the other hand user can't  change globally  header layout. Global layout always fixed.

**Comment by codepixar** [comment]
@cristianraiber - Would you like to move this option into the Customizer ?

**Comment by cristianraiber** [comment]
@codepixar - you should have some settings in the Customizer that act as defaults/globals. Basically, you can overwrite these settings per page/post/custom-post-type if you want to, but globally, they'd be set from within the Customizer.

Does this make sense to you?

**Comment by codepixar** [comment]
@cristianraiber - I have already done this issue  in previous PR, Please check.

**Comment by cristianraiber** [comment]
@codepixar - Will do. Please see all my other comments.

**Comment by cristianraiber** [comment]
This now works as advertised. Good job!
