### ISSUE TITLE
Escaping on the frontend

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#18]
You're missing escape functions, well, basically everywhere. I'd try referencing a single line to show an example, but it's everywhere.

Here is an example though from your latest PR: https://github.com/ColorlibHQ/fashe-wp/pull/17/commits/7a65a8fd3693ce246a5d6627fc5c7d85cbfd04f8#diff-10ee06f8a8fc516a9b67c562575f8d69R88

I recommend giving the Codex a read re. this: https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data

In your case, you could handle the escaping inside the function `fashe_opt`

**Comment by codepixar** [comment]
Already done, Please check.

**Comment by cristianraiber** [comment]
@codepixar - This is far from being done and I think it's one of the biggest issues of how you coded these themes.

It's impossible for me to list all the discrepancies here as that would make for a very long ticket, but here's just a few examples of how you're doing this wrong:

https://github.com/ColorlibHQ/fashe-wp/blob/master/inc/hooks/hooks-functions.php#L297

- You are escaping an option than is numeric, using `esc_html` instead of `absint` and then you're running this value through a function that returns the excerpt (aka: text) that's not being escaped through anything
- You should be escaping & concatenating individually here: https://github.com/ColorlibHQ/fashe-wp/blob/master/templates/404.php#L50
- Remember that almost no WP core function does escaping for you: https://github.com/ColorlibHQ/fashe-wp/blob/master/templates/content-audio.php#L18 (this issue persists across almost all template files)
- There's no escaping for `fashe_blog_posts_thumb_cb`&& *many more of your functions, please check them all*.

**Comment by cristianraiber** [comment]
I'm going to have another look at the end, when all the other issues are fixed over this. This is one of the more time consuming tasks. While I've looked through your commits re. this issue and it seemed to address everything I've said above, I'm still pretty sure it's not fixing all issues as you only committed related to the issues I mentioned above.

**Comment by codepixar** [comment]
@cristianraiber - I have trying to solve this issue, I have fixed some problem which i have catching. If there remaining  more issue please help me to catch them sometimes i'm confused in this case.

One thing I want share with you. You sad that to escaping fashe_blog_posts_thumb_cb but don't understand why and how ?  The function print thumb image or embedded video or audio. All dynamic data are already escaped In this function. Sorry for irritate you.

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - no need to comment on this ticket, I will do a final sweep and push fixes related to escaping/sanitsation. 

It's one of those situations where you need to use experience to implement it properly. Don't worry, escaping IS one of those confusing topics that no one usually likes to deal with haha. 

My team will address this. @puikinsh - if you want me to detail this for @codepixar so they fix it, just reply here.

**Comment by cristianraiber** [comment]
@cristian-e - we just need to do a comb through the themes' code and look for errors in escaping / sanitization.
