### ISSUE TITLE
No recommended action to import demo content

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#19]
Only recommended action concerns installing One Click Demo Import from ProteusThemes

**Comment by codepixar** [comment]
@cristianraiber  - In this issue i'm just adding note, see this screenshot http://prntscr.com/l89h5x. If i want to  better solution i need to work in epsilon core which is not possible because epsilon use as submodule.

**Comment by cristianraiber** [comment]
@codepixar - you can always set an action and check if a certain post title exists. Make sure you add one in your demo content, then, check if it exists or not. If it doesn't, you show the recommended action of importing the demo content.

**Comment by codepixar** [comment]
@cristianraiber - I was trying to do something like that. If i want to do this i need some event and implement some code in epsilon core. I'm trying but nothing happened. I can't make any idea how i do this.

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - you don't need anything fancy like that. Just create a hidden customizer (or post_meta, if you want to and feel it's easier) setting with a unique value. 

Something like: "codepixar_imported_demo: true". 

Then, you create a recommended action that checks if this value exists or not. It will only come when the demo import will run successfully. 

Does this make sense to you?

**Comment by codepixar** [comment]
@cristianraiber - Fixed this issue please check http://prntscr.com/laclgi

**Comment by cristianraiber** [comment]
This is now properly implemented. Good job.
