### ISSUE TITLE
Why WeGlot needed for demo content !?

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#2]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/7841556/46740447-86552100-ccab-11e8-978c-e1c289f1eed7.png">

**Comment by codepixar** [comment]
@cristianraiber - WeGlot plugin used for Translate language change option. It's no need for demo content, it was mistake in new PR  WeGlot remove from action and implement in recommended plugin.
