### ISSUE TITLE
Changing global header layout does nothing

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#20]
<img width="1820" alt="image" src="https://user-images.githubusercontent.com/7841556/47218812-a7a5c380-d3b5-11e8-98e4-c00ada682257.png">

**Comment by cristianraiber** [comment]
@codepixar - selecting any of the 3 values, doesn't do anything.

**Comment by cristianraiber** [comment]
*LE*: It looks like it does work, but not on the homepage?

**Comment by codepixar** [comment]
@cristianraiber - Global header layout work without custom home page. Custom home page header layout set from meta field. 
http://prntscr.com/l87jtz

**Comment by cristianraiber** [comment]
Why have you made this so utterly complicated? Please force Global to work everywhere UNLESS I choose anything (but the default) from post meta. 

Otherwise, global header layout is useless.

**Comment by codepixar** [comment]
Already done, Please check.

**Comment by cristianraiber** [comment]
@codepixar - You have now removed this: https://prnt.sc/l87jtz. Why? Both should co-exist. If users want to overwrite the global value of the header, per page, they should be able to do so.

**Comment by codepixar** [comment]
@cristianraiber - I don't remove meta option  http://prntscr.com/l9ajlm.To get update options you need to use update theme and update fashe companion plugin.

**Comment by codepixar** [comment]
@cristianraiber - Is checked this issue?

**Comment by cristianraiber** [comment]
@codepixar - it looks like the option was there, but I missed it because it's fairly hidden. 

Also, this metabox doesn't show up in Gutenberg:

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/7841556/47419805-a72a7580-d785-11e8-9911-2fafdc9b623f.png">

**Comment by cristianraiber** [comment]
@codepixar - I checked your last PR, but this still doesn't show up when using Gutenberg.

**Comment by codepixar** [comment]
@cristianraiber - Fixed this issue please check.

**Comment by cristianraiber** [comment]
@codepixar - still doesn't work at my end with latest Gutenberg & Fashe / fashe companion.

**Comment by codepixar** [comment]
@ cristianraiber - Sorry for inconvenience some how css file not update last PR.

**Comment by codepixar** [comment]
@ cristianraiber - I was forgot to PR update commit. Please check fashe companion.

**Comment by cristianraiber** [comment]
@codepixar - Yes, now it works. Good job!
