### ISSUE TITLE
Control shouldn't show IF WeGlot isn't installed

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#23]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/7841556/47219059-66fa7a00-d3b6-11e8-9f77-f92d8d6defd6.png">

**Comment by cristianraiber** [comment]
There's no reason this is showing IF the WeGlot plugin isn't installed.

**Comment by codepixar** [comment]
Already done, Please check.
