### ISSUE TITLE
Big difference between Customizer & LIVE

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#24]
Customizer back-end:
---
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/7841556/47219230-eee08400-d3b6-11e8-9c37-2630933d84b1.png">

**Comment by cristianraiber** [comment]
Live front-end:
---
<img width="1874" alt="image" src="https://user-images.githubusercontent.com/7841556/47219259-04ee4480-d3b7-11e8-8ce6-89327016a2b4.png">

**Comment by codepixar** [comment]
Already done, Please check.

**Comment by cristianraiber** [comment]
@codepixar - still not done:

Customizer:
---
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/7841556/47293335-868dde80-d612-11e8-8c59-8ae5d6dbb657.png">

**Comment by cristianraiber** [comment]
Live:
---

<img width="1870" alt="image" src="https://user-images.githubusercontent.com/7841556/47293353-94436400-d612-11e8-9f58-d583e8d281d7.png">

**Comment by codepixar** [comment]
@cristianraiber - I don't find difference without header top text color and cart icon left margin in your screenshot. I have already add left margin in cart icon in last PR and text color has no problem in my machine http://prntscr.com/l9edhs  http://prntscr.com/l9ed4s

**Comment by cristianraiber** [comment]
@codepixar - yeah, that only works if you change the value. However, for the default value, it looks like above in my screenshots. Please fix.

**Comment by codepixar** [comment]
@cristianraiber - Fixed this issue please check.

**Comment by codepixar** [comment]
@cristianraiber - This issue was fixed. Please check.
