### ISSUE TITLE
Class error

### ISSUE THREAD

**Issue by mantasdev1** [ColorlibHQ/fashe-wp#29]
When activating theme, this error occurs:

Fatal error: Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /../public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php:172 Stack trace: #0 /../public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus() #1 /../public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme)) #2 /.../public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(56): Epsilon_init_Dashboard::get_instance() #3 /.../public_html/wp-content/themes/fashe-wp-master/inc/classes/Class-Config.php(41): Fashe->init() #4 /.../public_html/wp-content/themes/fashe-wp-master/functions.php(99): Fashe->__construct() #5 /.../public_html/wp-settings.php(426): include(' in /.../public_html/wp-content/themes/fashe-wp-master/inc/class-epsilon-init-dashboard.php on line 172

**Comment by cristianraiber** [comment]
@mantasdev1 - you shouldn't rely on GitHub to download the theme ZIP. Once this theme is fully released, it will be advertised on Colorlib.com with proper download links. 

Right now, this repository uses Github sub-modules which, GitHub, doesn't add to ZIP when you download, automatically. If you use a GitHub client, you can follow this tutorial: 
https://github.com/ColorlibHQ/activello#repository-clonedownload-fire-fire-fire
