### ISSUE TITLE
Why no demo content importer through Epsilon Framework?

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#3]
I only see a huge list of recommended actions, no demo content present.

**Comment by cristianraiber** [comment]
There is no need for Demo Importer from ProteusThemes when you're using Epsilon Framework. Same thing happened for Philosophy.

**Comment by codepixar** [comment]
@cristianraiber - Fashe theme built with elementor and custom meta in this case i think  it is not possible  to use Epsilon Framework demo import system, thats why i used one click demo importer.

**Comment by cristianraiber** [comment]
@codepixar - Ah, ok.
