### ISSUE TITLE
Update readme.txt

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#31]
@codepixar - For this theme to be accepted on w.org, you need to update readme.txt file to mention ALL theme images/scripts/styles uses with corresponding licensing.

See this: https://github.com/ColorlibHQ/Mosh/blob/master/readme.txt

**Comment by codepixar** [comment]
@cristianraiber  - I have update readme file. One question, Will i re upload image from pixabay.com ?

**Comment by cristianraiber** [comment]
@codepixar - yep, you should re-upload from Pixabay.com. Also, StockSnap.io is a good source of images.

**Comment by codepixar** [comment]
@cristianraiber  - we have re upload image from pixabay.com and update readme txt file. Please check.
