### ISSUE TITLE
Outdated Woo templates

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#33]
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/7841556/47563747-797f3100-d92b-11e8-9b93-5836c313036f.png">

**Comment by codepixar** [comment]
@cristianraiber - Update the WooCommerce  Outdated template. Please check.

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - https://github.com/ColorlibHQ/fashe-wp/blob/master/woocommerce/single-product/add-to-cart/simple.php#L15

This is just one example. Here is the full list.

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/7841556/47616135-42db1f00-dac1-11e8-9f5c-f01976dbeb2a.png">

**Comment by codepixar** [comment]
@cristianraiber  - I have already removed the file ![image](https://user-images.githubusercontent.com/43398174/47616427-c9eebe00-dae6-11e8-9f23-4bedf1c7cd33.png)

**Comment by cristianraiber** [comment]
@codepixar - Please, by the end of this week, address all issues remaining in GitHub here. It's a very simple theme with too many bugs. 

Focus on getting them done all at once so I have something to check, not one by one, please. 

Thank you!

cc @puikinsh

**Comment by codepixar** [comment]
@cristianraiber  - We have already fixed this issue in previous PR. Please check screenshot http://prntscr.com/lbr1u4

**Comment by cristianraiber** [comment]
@codepixar - yes, it looks like my deployment script had a bug where it wasn't removing previously deployed files. Basically, the old files were still there.

Cleaning up the deployment folder and make a new deploy with the latest files fixed the issue. 👍
