### ISSUE TITLE
Theme Options -> WooCommerce options

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#8]
It looks like the page you're redirecting to, isn't the actual shop page.

**Comment by cristianraiber** [comment]
- Where does "Related product per page" actually work? 
- Shop title show/hide doesn't do anything. 

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/7841556/46741257-5444be80-ccad-11e8-8144-9962f933f78c.png">

**Comment by cristianraiber** [comment]
- Epsilon Framework comes with range slider controls. Please use these instead of input texts (what you've used) where users enter numbers right now. 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/7841556/46741335-7b9b8b80-ccad-11e8-9040-3c492c9eda41.png">

**Comment by codepixar** [comment]
@cristianraiber - I have completed this issue in the last PR. Please check.

**Comment by cristianraiber** [comment]
@codepixar - please send a link to the line where you modified this. Thank you!

**Comment by codepixar** [comment]
@cristianraiber -  Please check this screenshot  http://prntscr.com/l6pyc6

Thank you.

**Comment by cristianraiber** [comment]
@codepixar - ok, I will check this.

**Comment by cristianraiber** [comment]
@codepixar - 

- I still can not find the usage of this setting: 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/7841556/47292360-5d1f8380-d60f-11e8-8554-d033f3c7da3b.png">

**Comment by cristianraiber** [comment]
@codepixar:

- [x] There should be an option here to show/hide related products on the individual products page. Right now, I can only select if I want to display 1 or more, I can not hide that area. 
- [x] You should add some titles or better group these settings because one of them controls the number of items displayed in the main shop page, the other the number of related items on the individual product page. Users need to know to click on the individual product page to see the "related products" setting taking effect.

**Comment by cristianraiber** [comment]
@codepixar - You still haven't answered me where I can see this option working: 
https://github.com/ColorlibHQ/fashe-wp/issues/8#issuecomment-431821097

**Comment by codepixar** [comment]
@cristianraiber - When you set shop page from http://prntscr.com/l9f96x then it will show shop title http://prntscr.com/l9f8dl

**Comment by cristianraiber** [comment]
@codepixar - I think this should be part of your demo content import :) Since you are already creating the shop page through your demo content, you should update this WooCommerce option as well to associate it with this page. 

It's easy to do, just an option to update.

**Comment by codepixar** [comment]
@cristianraiber  - Fixed this issue please check.

**Comment by cristianraiber** [comment]
@codepixar 

<img width="1822" alt="image" src="https://user-images.githubusercontent.com/7841556/47564156-b0097b80-d92c-11e8-9502-13222c7944aa.png">

**Comment by cristianraiber** [comment]
Show title option is turned OFF, title still appears.

**Comment by codepixar** [comment]
@cristianraiber - Please check this screenshot http://prntscr.com/lbbda0

**Comment by cristianraiber** [comment]
@codepixar - the text was misleading, I thought it means the big title of the page, not the small one.
