### ISSUE TITLE
Header Colors don't work

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/fashe-wp#9]
<img width="1857" alt="image" src="https://user-images.githubusercontent.com/7841556/46741424-a7b70c80-ccad-11e8-8a7a-099c9f653e3f.png">

**Comment by cristianraiber** [comment]
Please use only color pickers from Epsilon. Right now you're using a mix of WP Core color pickers & Epsilon.

**Comment by codepixar** [comment]
Already done, Please check.

**Comment by cristianraiber** [comment]
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/7841556/47292747-a3291700-d610-11e8-8fb2-0a432c6c5a6c.png">

**Comment by cristianraiber** [comment]
This doesn't look done to me.

**Comment by codepixar** [comment]
@cristianraiber - This option work on default pages like http://prntscr.com/l8zq3k

**Comment by cristianraiber** [comment]
@codepixar - Then you will have to figure out a way to properly place these colors or rename them. Right now, they are very misleading and makes you think like they are for the whole theme.

**Comment by cristianraiber** [comment]
@codepixar - this still needs an answer.

**Comment by codepixar** [comment]
@ cristianraiber - I have already rename Color section name to Header Color. Would you like this? 
http://prntscr.com/l9r1ix

**Comment by cristianraiber** [comment]
@codepixar - yep, that's totally fine.
